
// Objective-C API for talking to the following Go packages
//
//	googleapi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoogleApi_FRAMEWORK_H__
#define __GoogleApi_FRAMEWORK_H__

#include "Googleapi.objc.h"
#include "Universe.objc.h"

#endif
