// Objective-C API for talking to googleapi Go package.
//   gobind -lang=objc googleapi
//
// File is generated by gobind. Do not edit.

#ifndef __Googleapi_H__
#define __Googleapi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GoogleapiTextReturner;

/**
 * Greeter greets people.
 */
@interface GoogleapiTextReturner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

FOUNDATION_EXPORT GoogleapiTextReturner* _Nullable GoogleapiNewGreeter(NSString* _Nullable text);

// skipped function ReturnText with unsupported parameter or return types


#endif
